import {FunctionalElement} from 'element-vir';
import {Vir_2022_08_03} from '../challenges/vir-2022-08-03.element';
import {Vir_2022_08_04} from '../challenges/vir-2022-08-04.element';

/**
 * This file is automatically generated by the combine-challenges-into-app.ts script. If you edit
 * this manually, it will ger overwritten!
 */

export type ChallengeDefinition = {
    element: FunctionalElement;
    date: Date;
};

export const allChallenges: readonly Readonly<ChallengeDefinition>[] = [
    {
        element: Vir_2022_08_03,
        date: new Date('2022-08-03'),
    },
    {
        element: Vir_2022_08_04,
        date: new Date('2022-08-04'),
    },
] as const;
